'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, BookOpen, Clock3, Layers3, PlaySquare, Plus, Radio, Sparkles, Users, X } from 'lucide-react';
import Loading from './Loading';
import WorkspaceSidebar from './WorkspaceSidebar';

type Room = { id:string; name:string; description?:string|null; mode:string; updatedAt:string; members:number; executions:number; role:string };

export default function DashboardClient(){
  const [user,setUser]=useState<any>(null); const [rooms,setRooms]=useState<Room[]>([]); const [metrics,setMetrics]=useState<any>(null); const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [mode,setMode]=useState('PAIR'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
  async function load(){ const me=await fetch('/api/auth/me'); if(!me.ok){window.location.href='/login';return;} const mj=await me.json(); setUser(mj.user); const [r,m]=await Promise.all([fetch('/api/rooms'),fetch('/api/metrics')]); if(r.ok)setRooms((await r.json()).rooms); if(m.ok)setMetrics(await m.json()); setLoading(false); }
  useEffect(()=>{load();},[]);
  async function createRoom(){ setBusy(true); setError(''); const res=await fetch('/api/rooms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,description,mode})}); const json=await res.json(); setBusy(false); if(!res.ok){setError(json.error??'Could not create room.');return;} window.location.href=`/room/${json.roomId}`; }
  const counts = useMemo(() => { const c = Object.fromEntries((metrics?.executionCounts??[]).map((x:any)=>[x.status,x._count._all])); return { completed:c.COMPLETED??0, failed:(c.FAILED??0)+(c.TIMEOUT??0), queued:(c.QUEUED??0)+(c.RUNNING??0) }; }, [metrics]);
  if(loading)return <div className="page-shell"><Loading label="Loading your workspace…"/></div>;
  return <div className="workspace-frame"><WorkspaceSidebar user={user} onCreate={()=>setOpen(true)}/><main className="workspace-main dashboard-main">
    <div className="dashboard-hero animate-in"><div><div className="eyebrow">Command centre</div><h1>Good to see you, {user?.name.split(' ')[0]}.</h1><p>Rooms, execution health and collaborative sessions — all in one quiet workspace.</p></div><button className="button button-gold button-large" onClick={()=>setOpen(true)}><Plus size={17}/> New room</button></div>
    <section className="stat-grid dashboard-stats">
      <div className="panel stat-card metric-accent animate-in stagger-1"><div className="stat-icon"><Layers3 size={17}/></div><div className="label">Your rooms</div><div className="value">{rooms.length}</div><span className="metric-note">Active workspaces</span></div>
      <div className="panel stat-card animate-in stagger-2"><div className="stat-icon"><Users size={17}/></div><div className="label">Collaborators reached</div><div className="value">{rooms.reduce((a,r)=>a+r.members,0)}</div><span className="metric-note">Across your rooms</span></div>
      <div className="panel stat-card animate-in stagger-3"><div className="stat-icon"><PlaySquare size={17}/></div><div className="label">Executions</div><div className="value">{counts.completed}</div><span className="metric-note">{counts.failed} failed or timed out</span></div>
      <div className="panel stat-card animate-in stagger-4"><div className="stat-icon"><Radio size={17}/></div><div className="label">Queue activity</div><div className="value">{counts.queued + (metrics?.queueCounts?.waiting??0)}</div><span className="metric-note">Jobs moving through the worker pool</span></div>
    </section>
    <section className="dashboard-grid">
      <div className="panel dashboard-panel animate-in stagger-2"><div className="panel-head"><div><div className="section-kicker"><Sparkles size={15}/> Your rooms</div><h2>Recent workspaces</h2></div><span className="badge">{rooms.length} total</span></div>{rooms.length===0?<div className="empty-state compact-empty"><BookOpen size={32}/><h3>No rooms yet</h3><p>Create your first collaborative coding workspace.</p><button className="button button-gold" onClick={()=>setOpen(true)}>Create room</button></div>:<div className="room-grid dashboard-room-grid">{rooms.map((room,idx)=><article key={room.id} className="room-card elevated-card animate-in" style={{animationDelay:`${idx*45}ms`}}><div className="room-card-top"><span className="badge badge-gold">{room.mode}</span><span className="room-updated"><Clock3 size={12}/>{new Date(room.updatedAt).toLocaleDateString()}</span></div><h3>{room.name}</h3><p>{room.description||'A focused collaborative coding room.'}</p><div className="card-meta"><span><Users size={13}/> {room.members} members</span><span><PlaySquare size={13}/> {room.executions} runs</span></div><div className="room-card-actions"><Link href={`/room/${room.id}`} className="button button-accent">Open <ArrowUpRight size={15}/></Link><Link href={`/room/${room.id}/replay`} className="button button-ghost">Replay</Link></div></article>)}</div>}</div>
      <aside className="dashboard-side-stack">
        <div className="panel insight-card animate-in stagger-3"><div className="section-kicker"><BookOpen size={15}/> Quick start</div><h2>Run a focused session.</h2><p>Choose Interview for hidden tests, Pair for shared editing, or Team for a small group room.</p><button className="button button-gold wide" onClick={()=>setOpen(true)}>Create workspace</button></div>
        <div className="panel insight-card dark-accent animate-in stagger-4"><div className="section-kicker"><Radio size={15}/> System pulse</div><div className="pulse-grid"><div><span>Queued</span><strong>{metrics?.queueCounts?.waiting??0}</strong></div><div><span>Active</span><strong>{metrics?.queueCounts?.active??0}</strong></div><div><span>Delayed</span><strong>{metrics?.queueCounts?.delayed??0}</strong></div><div><span>Completed</span><strong>{metrics?.queueCounts?.completed??0}</strong></div></div></div>
      </aside>
    </section>
    {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="modal premium-modal" onMouseDown={e=>e.stopPropagation()}><button className="icon-button modal-close" onClick={()=>setOpen(false)}><X size={16}/></button><div className="eyebrow">New workspace</div><h2>Create a room</h2><p>Set the room tone first. You can add the coding challenge after creation.</p><div className="form-grid"><div className="field"><label>Room name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="DSA Interview — Round 1" autoFocus /></div><div className="field"><label>Description</label><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional context for collaborators" /></div><div className="field"><label>Mode</label><select value={mode} onChange={e=>setMode(e.target.value)}><option value="PAIR">Pair programming</option><option value="INTERVIEW">Technical interview</option><option value="TEAM">Team session</option></select></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="button button-ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="button button-gold" disabled={!name.trim()||busy} onClick={createRoom}>{busy?'Creating…':'Create room'}</button></div></div></div></div>}
  </main></div>;
}
