'use client';
import { useEffect, useState } from 'react';
import { Check, Mail, Save, ShieldCheck, UserRound } from 'lucide-react';
import Loading from './Loading';
import WorkspaceSidebar from './WorkspaceSidebar';

export default function ProfileClient(){
  const [user,setUser]=useState<any>(null); const [name,setName]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  useEffect(()=>{fetch('/api/auth/me').then(async r=>{if(!r.ok){window.location.href='/login';return;}const j=await r.json();setUser(j.user);setName(j.user.name);setLoading(false);}).catch(()=>window.location.href='/login')},[]);
  async function save(){setBusy(true);setMessage('');setError('');const r=await fetch('/api/auth/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name})});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error??'Could not update profile.');setUser(j.user);setMessage('Profile saved.');}
  if(loading)return <div className="page-shell"><Loading label="Loading profile…"/></div>;
  return <div className="workspace-frame"><WorkspaceSidebar user={user}/><main className="workspace-main"><div className="page-heading animate-in"><div><div className="eyebrow">Profile</div><h1>Your identity in CodeRoom.</h1><p>Keep the public details on your rooms polished and consistent.</p></div></div><div className="settings-grid"><section className="panel settings-card animate-in stagger-1"><div className="profile-hero"><div className="avatar profile-avatar">{user.name.slice(0,1).toUpperCase()}</div><div><div className="badge badge-gold">Account</div><h2>{user.name}</h2><p>{user.email}</p></div></div><div className="form-grid"><div className="field"><label>Display name</label><div className="input-with-icon"><UserRound size={16}/><input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></div></div><div className="field"><label>Email address</label><div className="input-with-icon"><Mail size={16}/><input value={user.email} readOnly/></div></div>{error&&<div className="form-error">{error}</div>}{message&&<div className="success-note"><Check size={15}/>{message}</div>}<button className="button button-gold" onClick={save} disabled={busy||!name.trim()}><Save size={15}/>{busy?'Saving…':'Save profile'}</button></div></section><section className="panel settings-card animate-in stagger-2"><div className="section-kicker"><ShieldCheck size={16}/> Security posture</div><h2>Private by default.</h2><p className="muted-copy">CodeRoom keeps authentication sessions server-side and records security-sensitive account and room actions for auditability.</p><div className="security-list"><div><strong>Session cookie</strong><span>HTTP-only and same-site</span></div><div><strong>Password storage</strong><span>scrypt-based password hashing</span></div><div><strong>Room access</strong><span>Membership checked server-side</span></div></div></section></div></main></div>;
}
