'use client';
import { useEffect, useState } from 'react';
import Editor from '@monaco-editor/react';
import { ArrowLeft, Clock3, FileCode2, UserCircle2 } from 'lucide-react';
import Link from 'next/link';
import Loading from './Loading';
import { useTheme } from './ThemeProvider';

export default function ReplayClient({roomId}:{roomId:string}){const{theme}=useTheme();const[events,setEvents]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[loading,setLoading]=useState(true);useEffect(()=>{fetch(`/api/rooms/${roomId}/events`).then(r=>r.json()).then(j=>{setEvents(j.events||[]);setSelected((j.events||[]).at(-1)||null);setLoading(false);});},[roomId]);if(loading)return <div className="page-shell"><Loading label="Loading session history…"/></div>;const snapshot=selected?.payload?.snapshot ?? '// Select an edit event to inspect a file snapshot.'; const replayLanguage=selected?.payload?.language==='cpp'?'cpp':selected?.payload?.language==='java'?'java':selected?.payload?.language==='javascript'?'javascript':selected?.payload?.language==='typescript'?'typescript':'python';return <main className="replay-layout"><aside className="timeline"><Link href={`/room/${roomId}`} className="text-button" style={{marginBottom:12}}><ArrowLeft size={15}/> Back to room</Link><h2>Session replay</h2>{events.map(event=><button key={event.id} className={`timeline-item ${selected?.id===event.id?'active':''}`} onClick={()=>setSelected(event)}><div className="time">{new Date(event.createdAt).toLocaleTimeString()}</div><div className="type">{event.type.replaceAll('_',' ')}</div><div style={{color:'var(--muted)',fontSize:11,marginTop:2}}><UserCircle2 size={11} style={{verticalAlign:'-2px'}}/> {event.user}</div></button>)}</aside><section className="replay-preview"><div className="replay-card"><div className="output-head"><div><div className="output-title">{selected?.payload?.fileName || 'Event detail'}</div><div className="room-subtitle"><Clock3 size={11} style={{verticalAlign:'-2px'}}/> {selected?new Date(selected.createdAt).toLocaleString():'—'}</div></div>{selected?.type==='EDIT'&&<span className="badge"><FileCode2 size={12}/> Snapshot</span>}</div><Editor height="100%" theme={theme==='dark'?'vs-dark':'vs'} defaultLanguage={replayLanguage} value={snapshot} options={{readOnly:true,minimap:{enabled:false},fontSize:13,automaticLayout:true,scrollBeyondLastLine:false}}/></div></section></main>}
