'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Check, KeyRound, Lock, Palette, Save, Shield, Sparkles } from 'lucide-react';
import Loading from './Loading';
import WorkspaceSidebar from './WorkspaceSidebar';
import { useTheme } from './ThemeProvider';
import ThemeToggle from './ThemeToggle';

export default function SettingsClient(){
  const [user,setUser]=useState<any>(null); const [loading,setLoading]=useState(true); const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirm,setConfirm]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const {theme,toggle}=useTheme();
  useEffect(()=>{fetch('/api/auth/me').then(async r=>{if(!r.ok){window.location.href='/login';return;}setUser((await r.json()).user);setLoading(false)}).catch(()=>window.location.href='/login')},[])
  async function changePassword(e:FormEvent){e.preventDefault();setError('');setMessage('');if(next!==confirm)return setError('New passwords do not match.');setBusy(true);const r=await fetch('/api/auth/password',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({currentPassword:current,newPassword:next})});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error??'Could not change password.');setCurrent('');setNext('');setConfirm('');setMessage('Password updated successfully.')}
  if(loading)return <div className="page-shell"><Loading label="Loading settings…"/></div>;
  return <div className="workspace-frame"><WorkspaceSidebar user={user}/><main className="workspace-main"><div className="page-heading animate-in"><div><div className="eyebrow">Settings</div><h1>Make CodeRoom feel yours.</h1><p>Appearance, account security and workspace preferences.</p></div></div><div className="settings-grid"><section className="panel settings-card animate-in stagger-1"><div className="settings-row-head"><div><div className="section-kicker"><Palette size={16}/> Appearance</div><h2>Royal by default.</h2><p className="muted-copy">Light mode uses the soft peach palette you chose. Dark mode shifts into a richer midnight-and-gold texture.</p></div><ThemeToggle/></div><div className="theme-preview-row"><button className={`theme-preview light-preview ${theme==='light'?'selected':''}`} onClick={()=>theme==='dark'&&toggle()}><span>Light</span><small>FFE5D9 + ivory</small></button><button className={`theme-preview dark-preview ${theme==='dark'?'selected':''}`} onClick={()=>theme==='light'&&toggle()}><span>Dark</span><small>Midnight + polished gold</small></button></div></section><section className="panel settings-card animate-in stagger-2"><div className="section-kicker"><Lock size={16}/> Security</div><h2>Change password</h2><form className="form-grid" onSubmit={changePassword}><div className="field"><label>Current password</label><div className="input-with-icon"><KeyRound size={16}/><input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/></div></div><div className="field"><label>New password</label><div className="input-with-icon"><KeyRound size={16}/><input type="password" autoComplete="new-password" minLength={8} value={next} onChange={e=>setNext(e.target.value)} required/></div></div><div className="field"><label>Confirm new password</label><div className="input-with-icon"><KeyRound size={16}/><input type="password" autoComplete="new-password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></div></div>{error&&<div className="form-error">{error}</div>}{message&&<div className="success-note"><Check size={15}/>{message}</div>}<button className="button button-gold" disabled={busy}><Save size={15}/>{busy?'Updating…':'Update password'}</button></form></section><section className="panel settings-card animate-in stagger-3"><div className="section-kicker"><Shield size={16}/> Product posture</div><div className="settings-list"><div><strong>Authentication</strong><span>Cookie-backed server sessions with rate-limited login.</span></div><div><strong>Execution isolation</strong><span>Disposable Docker sandboxes with resource controls.</span></div><div><strong>Auditability</strong><span>Room and account events are retained for session review.</span></div></div></section></div><div className="footer-signature"><Sparkles size={15}/> Crafted for focused collaborative engineering.</div></main></div>;
}
